# calculate N50 value, using contigs.fa generated by velvet as input
from Bio import SeqIO

records = SeqIO.parse("contigs.fa", "fasta")
n=0
seq_lengths = [len(seq_record) for seq_record in SeqIO.parse("contigs.fa", "fasta")]

#nlist = [repr(seq_record.seq).count('n') for seq_record in SeqIO.parse("contigs.fa", "fasta")]
total_length = sum(seq_lengths)
#n=sum(nlist)
seq_lengths.sort()
seq_lengths.reverse()
sum = 0
#print(n)
print(total_length)
print(total_length/2)
print(seq_lengths)



for seq_length in seq_lengths:
    sum += seq_length
    if sum >= total_length/2:
        print("N50 is", seq_length)
        break
    else:
        continue
'''
for record in SeqIO.parse("contigs.fa", "fasta"):
    print(record.seq)
    #print(len(record))'''

