/data/part2/software/admixture_linux-1.3.0/admixture --cv -j12 output.bed 1 | tee output.bed.1.log
/data/part2/software/admixture_linux-1.3.0/admixture --cv -j12 output.bed 2 | tee output.bed.2.log
/data/part2/software/admixture_linux-1.3.0/admixture --cv -j12 output.bed 3 | tee output.bed.3.log
/data/part2/software/admixture_linux-1.3.0/admixture --cv -j12 output.bed 4 | tee output.bed.4.log
/data/part2/software/admixture_linux-1.3.0/admixture --cv -j12 output.bed 5 | tee output.bed.5.log
/data/part2/software/admixture_linux-1.3.0/admixture --cv -j12 output.bed 6 | tee output.bed.6.log
/data/part2/software/admixture_linux-1.3.0/admixture --cv -j12 output.bed 7 | tee output.bed.7.log
/data/part2/software/admixture_linux-1.3.0/admixture --cv -j12 output.bed 8 | tee output.bed.8.log
/data/part2/software/admixture_linux-1.3.0/admixture --cv -j12 output.bed 9 | tee output.bed.9.log
/data/part2/software/admixture_linux-1.3.0/admixture --cv -j12 output.bed 10 | tee output.bed.10.log
